name: Erlang CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: 28

      - name: Install rebar3
        run: |
          wget https://s3.amazonaws.com/rebar3/rebar3
          chmod +x rebar3
          sudo mv rebar3 /usr/local/bin/

      - name: Compile modules with warnings
        run: |
          erl -noshell -eval "c(accRecursion20, [warn_all]), c(prime_sum, [warn_all]), init:stop()."

      - name: Run EUnit tests
        run: |
          erl -noshell -eval "eunit:test([accRecursion20, prime_sum]), init:stop()."
